-- Let's create a new tooltip from scratch using Ace Librarys
NuN_TooltipNew = CreateFrame("GameTooltip", "NuN_Tooltip", UIParent, "GameTooltipTemplate")
-- Pinned tooltip
NuN_PinnedTooltipNew = CreateFrame("GameTooltip", "NuN_PinnedTooltip", UIParent, "GameTooltipTemplate")
NuN_PinnedTooltipNew:SetSize(128, 64)
NuN_PinnedTooltipNew:EnableMouse(true)
NuN_PinnedTooltipNew:SetMovable(true)
NuN_PinnedTooltipNew:SetClampedToScreen(true)
NuN_PinnedTooltipNew:RegisterForDrag("LeftButton")
NuN_PinnedTooltipNew:SetScript("OnDragStart", function(self)
  self:StartMoving()
end)
NuN_PinnedTooltipNew:SetScript("OnDragStop", function(self)
  self:StopMovingOrSizing()
  NuN_FlagMoved()
end)

local PinnedTT_CloseButton = CreateFrame("Button", nil, NuN_PinnedTooltipNew)
PinnedTT_CloseButton:SetPoint("TOPRIGHT", 1, 0)
PinnedTT_CloseButton:SetSize(32, 32)
PinnedTT_CloseButton:SetNormalTexture("Interface\\Buttons\\UI-Panel-MinimizeButton-Up")
PinnedTT_CloseButton:SetPushedTexture("Interface\\Buttons\\UI-Panel-MinimizeButton-Down")
PinnedTT_CloseButton:SetHighlightTexture("Interface\\Buttons\\UI-Panel-MinimizeButton-Highlight")
PinnedTT_CloseButton:SetScript("OnClick", function(self)
  HideUIPanel(NuN_PinnedTooltipNew)
end)

local PinnedTT_EditButton = CreateFrame("Button", nil, NuN_PinnedTooltipNew, "UIPanelButtonTemplate")
PinnedTT_EditButton:SetPoint("RIGHT", PinnedTT_CloseButton, "LEFT", 6, 0)
PinnedTT_EditButton:SetSize(24, 24)
PinnedTT_EditButton:SetScript("OnClick", function()
  NuN_PinnedTT_OnClick()
end)
PinnedTT_EditButton:SetScript("OnEnter", function(self)
  NuN_DisplayTooltip(self, "NUN_TT_PIN_EDIT_TXT")
end)
PinnedTT_EditButton:SetScript("OnLeave", function(self)
  NuN_TooltipNew:Hide()
end)
PinnedTT_EditButton:SetScript("OnHide", function(self)
  NuN_PinnedTT_OnHide()
end)
local ptt_edit_texture = PinnedTT_EditButton:CreateTexture()
ptt_edit_texture:SetHeight(10)
ptt_edit_texture:SetWidth(10)
ptt_edit_texture:SetPoint("CENTER")
ptt_edit_texture:SetTexture("Interface\\Buttons\\UI-GuildButton-PublicNote-Up")
